# Generated by Django 4.0.2 on 2022-02-03 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('eventType', models.CharField(default='event', editable=False, max_length=5, verbose_name='type')),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('startTime', models.CharField(max_length=5)),
                ('endTime', models.CharField(max_length=5)),
                ('description', models.TextField()),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
    ]
