# Generated by Django 4.0.2 on 2022-02-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_add_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='id',
            new_name='uid',
        ),
    ]
