# Generated by Django 4.0.2 on 2022-02-10 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_day_year_and_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
