# Generated by Django 4.0.4 on 2022-05-13 20:31

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_slug_date_not_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=colorfield.fields.ColorField(default='#d66118', image_field=None, max_length=18, samples=[('#06BEE1', 'Cyan'), ('#D90368', 'Rose'), ('#35CE8D', 'Caribbean Green'), ('#830fdb', 'Purple'), ('#1E2EDE', 'Blue')]),
        ),
    ]
