# Generated by Django 4.0.4 on 2022-05-13 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_add_colorfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('can_edit_events', 'Can add, edit, and delete events.')]},
        ),
    ]
