# Generated by Django 4.0.4 on 2022-05-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_add_event_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='viewPerms',
            field=models.CharField(choices=[('public', 'Everyone'), ('volunteers', 'Volunteers'), ('staff', 'Staff')], default='volunteers', max_length=10, verbose_name='Who can see this event'),
        ),
    ]
