# Generated by Django 4.0.2 on 2022-02-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_make_slug_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics', verbose_name='Profile Image'),
        ),
    ]
