# Generated by Django 4.1.2 on 2022-10-31 23:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField(blank=True, default='')),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('viewPerms', models.CharField(choices=[('public', 'Everyone'), ('volunteers', 'Volunteers'), ('staff', 'Staff')], default='volunteers', max_length=10, verbose_name='Who can see this announcement')),
                ('postedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
