# Generated by Django 4.0.4 on 2022-06-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_add_shifts_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseshift',
            name='endRepeat',
            field=models.DateField(blank=True, null=True, verbose_name='End Repeat'),
        ),
        migrations.AlterField(
            model_name='baseshift',
            name='repeat',
            field=models.CharField(choices=[(None, 'Do Not Repeat'), ('everyday', 'Everyday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=9, null=True),
        ),
    ]
