# Generated by Django 4.0.4 on 2022-07-05 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0004_add_date_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftInstance',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('startTime', models.TimeField(blank=True)),
                ('endTime', models.TimeField(blank=True)),
                ('name', models.CharField(blank=True, max_length=25)),
                ('description', models.TextField(blank=True)),
                ('staffSlots', models.IntegerField(blank=True)),
                ('volSlots', models.IntegerField(blank=True)),
                ('minSlots', models.IntegerField(blank=True, verbose_name='Minimum Staff/volunteers')),
                ('baseShift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.baseshift')),
                ('staff', models.ManyToManyField(blank=True, related_name='shift_staff', to=settings.AUTH_USER_MODEL)),
                ('vols', models.ManyToManyField(blank=True, related_name='shift_vols', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
