# Generated by Django 4.0.4 on 2022-07-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_add_ShiftInstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseshift',
            name='slots',
            field=models.IntegerField(default=10, verbose_name='Ideal Staff/Volunteers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftinstance',
            name='slots',
            field=models.IntegerField(default='10', verbose_name='Ideal Staff/Volunteers'),
            preserve_default=False,
        ),
    ]
