# Generated by Django 4.1.2 on 2022-11-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_add_slots_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftinstance',
            name='staffCount',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='shiftinstance',
            name='volCount',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
